# Generated by Django 3.2.10 on 2022-01-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_fecha_subida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fecha_subida',
        ),
        migrations.AddField(
            model_name='post',
            name='estatus',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='texto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
