# Generated by Django 3.2.10 on 2022-02-08 23:41

import builtins
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil_Usuario',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=builtins.id, serialize=False, to='auth.user')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, default='avatar/avatar.png', null=True, upload_to='avatar')),
            ],
        ),
        migrations.CreateModel(
            name='MensajeriaInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remitente', models.IntegerField(blank=True, null=True)),
                ('asunto', models.CharField(blank=True, max_length=100, null=True)),
                ('mensaje', ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
