# Generated by Django 4.0 on 2022-02-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeriainterna',
            name='mensaje',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
