# Generated by Django 4.0 on 2022-02-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0002_alter_mensajeriainterna_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeriainterna',
            name='remitente',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
