# Generated by Django 4.0 on 2022-02-06 01:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0003_alter_mensajeriainterna_remitente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeriainterna',
            name='mensaje',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True),
        ),
    ]
