# Generated by Django 4.0 on 2021-12-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Apellido', models.CharField(max_length=30)),
                ('Telefono', models.IntegerField()),
                ('Direccion', models.CharField(max_length=100)),
                ('Mail', models.EmailField(max_length=254)),
                ('Documento', models.IntegerField()),
            ],
        ),
    ]
