# Generated by Django 4.0 on 2021-12-28 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='Apellido',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='Documento',
            new_name='documento',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='Direccion',
            new_name='domicilio',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='Mail',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='Telefono',
            new_name='telefono',
        ),
    ]
