# Generated by Django 4.0 on 2021-12-31 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_apellido_clientes_apellido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='apellido',
            new_name='condicion_iva',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='documento',
            new_name='cuit',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='nombre',
        ),
        migrations.AddField(
            model_name='clientes',
            name='empresa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Maquinarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes')),
            ],
        ),
    ]
