# Generated by Django 4.0 on 2021-12-31 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_rename_apellido_clientes_condicion_iva_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arreglo_Maquinarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_arreglo', models.DateField(auto_now=True)),
                ('arreglo', models.CharField(max_length=200)),
                ('maquinaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.maquinarias')),
            ],
        ),
    ]
