# Generated by Django 4.0 on 2022-01-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_arreglo_maquinarias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
