# Generated by Django 4.0 on 2022-01-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_clientes_mail_alter_clientes_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arreglo_maquinarias',
            name='fecha_arreglo',
            field=models.DateField(null=True),
        ),
    ]
